name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"
main = "dist/main.js"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[vars]
# Defaults for all environments to avoid ReferenceError at runtime
CUSTOM_DOMAIN = "zhoubo416.workers.dev"
MODE = "production"
TARGET_UPSTREAM = ""

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "example.com"

[env.production]
name = "cloudflare-docker-proxy"
# routes = [
#   { pattern = "docker.libcuda.so", custom_domain = true },
#   { pattern = "quay.libcuda.so", custom_domain = true },
#   { pattern = "gcr.libcuda.so", custom_domain = true },
#   { pattern = "k8s-gcr.libcuda.so", custom_domain = true },
#   { pattern = "k8s.libcuda.so", custom_domain = true },
#   { pattern = "ghcr.libcuda.so", custom_domain = true },
#   { pattern = "cloudsmith.libcuda.so", custom_domain = true },
# ]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.libcuda.so", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
